name: Create Pulumi Demo
on: [create]
jobs:
  Exploring-Pulumi-Create:
    if: ${{ github.event.ref_type == 'branch' && startsWith(github.event.ref, 'dev.') }}
    runs-on: ubuntu-latest
    env:
      PULUMI_COMMAND: up
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Quck Sanity Test
        run: |
          ls ${{ github.workspace }}
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Install Dependencies
        working-directory: ./pulumi
        run: npm install
      - uses: pulumi/actions@v3
        with:
          command: ${{ env.PULUMI_COMMAND }}
          stack-name: ${{ github.event.ref }}
          work-dir: ./pulumi
          upsert: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          BRANCH_NAME: ${{ github.event.ref }}
          PULUMI_COMMAND: ${{ env.PULUMI_COMMAND }}
