name: Create Environment (Pulumi)
on: [create]
jobs:
  Create-Environment:
    if: ${{ github.event.ref_type == 'branch' && startsWith(github.event.ref, 'dev.') }}
    runs-on: ubuntu-latest
    env:
      PULUMI_COMMAND: up
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Pulumi Dependencies
        working-directory: ./pulumi
        run: npm install
      - name: Execute Pulumi
        uses: pulumi/actions@v3
        with:
          command: ${{ env.PULUMI_COMMAND }}
          stack-name: ${{ github.event.ref }}
          work-dir: ./pulumi
          upsert: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          BRANCH_NAME: ${{ github.event.ref }}
          PULUMI_COMMAND: ${{ env.PULUMI_COMMAND }}
      - name: Sanity Check (log endpoint variable)
        run: echo "Variable value is ${{ env.REACT_APP_REMOTE_ENDPOINT }}"
      - name: Install React Dependencies
        working-directory: ./react
        run: npm install
      - name: Build React
        working-directory: ./react
        run: npm run build
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Upload Front-End to Azure Blob Storage
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az storage blob upload-batch --account-name ${{ env.AZURE_STORAGE_ACCOUNT_NAME }} -d '$web' -s ./react/build
      - name: Azure Logout
        run: |
          az logout
