name: Create Pulumi Demo
on: [create]
jobs:
  Exploring-Pulumi:
    runs-on: ubuntu-latest
    steps:
      - name: Pulumi Configure Credentials
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: dev
          work-dir: pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
